### PR TITLE
add exit control

### PR DESCRIPTION
**Pull request by mvadu**
Current code only works in an interactive session since it only cleans up for Ctrl+C signal. If you are running this inside a non interactive sessions (e.g. docker) it will fail to clean up properly. This PR adds a threading event parameter, which can be set from outside to gracefully exit the blocking loop.

### CODE REVIEW

**Comment by colin-guyon** [comment]
Hello and thank you, I see the need.
I think of a very simple solution instead of a threading Event, that would be to return `False` in the handler when we want the listening to stop (any other value like `None` or `True` would make the listening continue).
Another solution could be that the handler could raise a `StopIteration` exception (for example) when he wants to stop the loop.
What do you think of that ?

**Comment by mvadu** [comment]
Why didn't I think of it!! I like both of your suggestions, and probably both (`return False` and  `StopIteration`) of them are easy enough to add without breaking existing consumers of this library. If you are okay I will update my PR with that implementation.

Personally I think `StopIteration` is better since existing code raises an exception to end the execution, so a consumer might have another catch to do their own cleaup.

**Comment by mvadu** [comment]
@colin-guyon submitted a commit with `StopIteration`. But I am not sure if `except StopIteration: raise` approach is the correct one. I am not python expert, so if you feel we should probably change, please let me know.

**Comment by colin-guyon** [comment]
@mvadu Ok so in this implementation you allow both possibilities, in the handler we can either return `False` or `raise StopIteration`, why not indeed. I thought we could only have one way to stop the loop from the handler, but in fact it may be convenient to allow both.
The `except StopIteration: raise` approach is good for me :) Please let me know if I can merge ;)
Thanks

**Comment by mvadu** [comment]
Awesome.. Please go ahead and merge.. My docker build is waiting for this 😁

**Pull request merged**
